service: milia-api

plugins:
  - serverless-plugin-warmup
  - serverless-offline

custom: 
  warmup:
    folderName: '_warmup'
    cleanFolder: false
    memorySize: 256
    name: '${self:service}-${self:provider.stage}-warmup-lambdas'
    timeout: 10
    prewarm: true

provider:
  name: aws
  runtime: nodejs10.x
  profile: ${self:provider.stage}
  stage: ${opt:stage, 'dev'}
  region: us-east-1
  memorySize: 256
  timeout: 10
  environment:
    SECRET_TOKEN: latheus
    REGION: ${self:provider.region}
    SERVERLESS_SERVICE: ${self:service}
    STAGE: ${self:provider.stage}
    GOOGLE_APPLICATION_CREDENTIALS: "./src/credentials/google.json"
  iamRoleStatements:
  - Effect: Allow
    Action:
      - dynamodb:DescribeTable
      - dynamodb:Query
      - dynamodb:Scan
      - dynamodb:GetItem
      - dynamodb:PutItem
      - dynamodb:UpdateItem
      - dynamodb:DeleteItem
    Resource: "*"

resources:
  - ${file(src/dynamodb.yml)}

functions:
  - ${file(src/functions.yml)}
