Resources:
  users:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:service}-${self:provider.stage}-users
      AttributeDefinitions:
        - AttributeName: email
          AttributeType: S               
      KeySchema:
        - AttributeName: email
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
  sessions:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:service}-${self:provider.stage}-user-session
      AttributeDefinitions:
        - AttributeName: accessToken
          AttributeType: S               
      KeySchema:
        - AttributeName: accessToken
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
  chatMessages:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:service}-${self:provider.stage}-user-messages
      AttributeDefinitions:
        - AttributeName: _id
          AttributeType: S
        - AttributeName: email
          AttributeType: S                                    
      KeySchema:
        - AttributeName: _id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: emailIndex
          KeySchema:
            - AttributeName: email
              KeyType: HASH
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: 1
            WriteCapacityUnits: 1                        
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
  trips:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:service}-${self:provider.stage}-user-actual-trip
      AttributeDefinitions:
        - AttributeName: email
          AttributeType: S               
      KeySchema:
        - AttributeName: email
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
  itinerary:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:service}-${self:provider.stage}-trip-itinerary
      AttributeDefinitions:
        - AttributeName: tripId
          AttributeType: S               
      KeySchema:
        - AttributeName: tripId
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1        
  timeline:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:service}-${self:provider.stage}-user-timeline-markers
      AttributeDefinitions:
        - AttributeName: _id
          AttributeType: S
        - AttributeName: email
          AttributeType: S                                    
      KeySchema:
        - AttributeName: _id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: emailIndex
          KeySchema:
            - AttributeName: email
              KeyType: HASH
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: 1
            WriteCapacityUnits: 1                        
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1                